"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import unittest

import cosmotech_api
from cosmotech_api.api.platform_api import PlatformApi  # noqa: E501


class TestPlatformApi(unittest.TestCase):
    """PlatformApi unit test stubs"""

    def setUp(self):
        self.api = PlatformApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_platform(self):
        """Test case for create_platform

        Create a new platform  # noqa: E501
        """
        pass

    def test_get_platform(self):
        """Test case for get_platform

        Get the details of the platform  # noqa: E501
        """
        pass

    def test_update_platform(self):
        """Test case for update_platform

        Update a platform  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
