"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 3.1.13
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.solution_role import SolutionRole


class TestSolutionRole(unittest.TestCase):
    """SolutionRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSolutionRole(self):
        """Test SolutionRole"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SolutionRole()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
