# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 4.0.0-onprem.7
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.solution_access_control import SolutionAccessControl

class TestSolutionAccessControl(unittest.TestCase):
    """SolutionAccessControl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SolutionAccessControl:
        """Test SolutionAccessControl
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SolutionAccessControl`
        """
        model = SolutionAccessControl()
        if include_optional:
            return SolutionAccessControl(
                id = '',
                role = ''
            )
        else:
            return SolutionAccessControl(
                id = '',
                role = '',
        )
        """

    def testSolutionAccessControl(self):
        """Test SolutionAccessControl"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
