"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 2.2.0
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.scenario_role import ScenarioRole


class TestScenarioRole(unittest.TestCase):
    """ScenarioRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScenarioRole(self):
        """Test ScenarioRole"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScenarioRole()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
