# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 4.0.1-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.twincache_status_enum import TwincacheStatusEnum

class TestTwincacheStatusEnum(unittest.TestCase):
    """TwincacheStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTwincacheStatusEnum(self):
        """Test TwincacheStatusEnum"""
        # inst = TwincacheStatusEnum()

if __name__ == '__main__':
    unittest.main()
