"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 1.1.3-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.delete_historical_data import DeleteHistoricalData


class TestDeleteHistoricalData(unittest.TestCase):
    """DeleteHistoricalData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteHistoricalData(self):
        """Test DeleteHistoricalData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteHistoricalData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
