"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 3.1.13
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.run_container_logs import RunContainerLogs


class TestRunContainerLogs(unittest.TestCase):
    """RunContainerLogs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunContainerLogs(self):
        """Test RunContainerLogs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RunContainerLogs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
