"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 3.1.13
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.file_upload_metadata import FileUploadMetadata
globals()['FileUploadMetadata'] = FileUploadMetadata
from cosmotech_api.model.file_upload_validation import FileUploadValidation


class TestFileUploadValidation(unittest.TestCase):
    """FileUploadValidation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileUploadValidation(self):
        """Test FileUploadValidation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileUploadValidation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
