"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 2.2.0
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.resource_size_info import ResourceSizeInfo
globals()['ResourceSizeInfo'] = ResourceSizeInfo
from cosmotech_api.model.run_template_resource_sizing import RunTemplateResourceSizing


class TestRunTemplateResourceSizing(unittest.TestCase):
    """RunTemplateResourceSizing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunTemplateResourceSizing(self):
        """Test RunTemplateResourceSizing"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RunTemplateResourceSizing()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
