# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 5.1.0
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.runner_status import RunnerStatus

class TestRunnerStatus(unittest.TestCase):
    """RunnerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunnerStatus(self):
        """Test RunnerStatus"""
        # inst = RunnerStatus()

if __name__ == '__main__':
    unittest.main()
