"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 2.2.0
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.resource_size_info import ResourceSizeInfo
globals()['ResourceSizeInfo'] = ResourceSizeInfo
from cosmotech_api.model.scenario_resource_sizing import ScenarioResourceSizing


class TestScenarioResourceSizing(unittest.TestCase):
    """ScenarioResourceSizing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScenarioResourceSizing(self):
        """Test ScenarioResourceSizing"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScenarioResourceSizing()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
