"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 3.1.13
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import cosmotech_api
from cosmotech_api.api.run_api import RunApi  # noqa: E501


class TestRunApi(unittest.TestCase):
    """RunApi unit test stubs"""

    def setUp(self):
        self.api = RunApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_run(self):
        """Test case for delete_run

        Delete a run  # noqa: E501
        """
        pass

    def test_get_run(self):
        """Test case for get_run

        Get the details of a run  # noqa: E501
        """
        pass

    def test_get_run_logs(self):
        """Test case for get_run_logs

        get the logs for the Run  # noqa: E501
        """
        pass

    def test_get_run_status(self):
        """Test case for get_run_status

        get the status for the Run  # noqa: E501
        """
        pass

    def test_list_runs(self):
        """Test case for list_runs

        get the list of Runs for the Runner  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
