"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.13-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.scenario_run_container_logs import ScenarioRunContainerLogs
globals()['ScenarioRunContainerLogs'] = ScenarioRunContainerLogs
from cosmotech_api.model.scenario_run_logs import ScenarioRunLogs


class TestScenarioRunLogs(unittest.TestCase):
    """ScenarioRunLogs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScenarioRunLogs(self):
        """Test ScenarioRunLogs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScenarioRunLogs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
