# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 4.0.0-onprem.7
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.workspace_file import WorkspaceFile

class TestWorkspaceFile(unittest.TestCase):
    """WorkspaceFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceFile:
        """Test WorkspaceFile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceFile`
        """
        model = WorkspaceFile()
        if include_optional:
            return WorkspaceFile(
                file_name = ''
            )
        else:
            return WorkspaceFile(
        )
        """

    def testWorkspaceFile(self):
        """Test WorkspaceFile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
