# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 5.0.1-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.file_upload_validation import FileUploadValidation

class TestFileUploadValidation(unittest.TestCase):
    """FileUploadValidation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileUploadValidation:
        """Test FileUploadValidation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileUploadValidation`
        """
        model = FileUploadValidation()
        if include_optional:
            return FileUploadValidation(
                nodes = [
                    cosmotech_api.models.file_upload_metadata.FileUploadMetadata(
                        name = '', 
                        size = 56, )
                    ],
                edges = [
                    cosmotech_api.models.file_upload_metadata.FileUploadMetadata(
                        name = '', 
                        size = 56, )
                    ]
            )
        else:
            return FileUploadValidation(
        )
        """

    def testFileUploadValidation(self):
        """Test FileUploadValidation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
