"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.simulation_start_scenario import SimulationStartScenario


class TestSimulationStartScenario(unittest.TestCase):
    """SimulationStartScenario unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimulationStartScenario(self):
        """Test SimulationStartScenario"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SimulationStartScenario()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
