"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 1.1.3-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.delete_historical_data import DeleteHistoricalData
from cosmotech_api.model.run_template_step_source import RunTemplateStepSource
globals()['DeleteHistoricalData'] = DeleteHistoricalData
globals()['RunTemplateStepSource'] = RunTemplateStepSource
from cosmotech_api.model.run_template import RunTemplate


class TestRunTemplate(unittest.TestCase):
    """RunTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunTemplate(self):
        """Test RunTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RunTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
