# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 5.0.0-beta3
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.organization_update_request import OrganizationUpdateRequest

class TestOrganizationUpdateRequest(unittest.TestCase):
    """OrganizationUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationUpdateRequest:
        """Test OrganizationUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationUpdateRequest`
        """
        model = OrganizationUpdateRequest()
        if include_optional:
            return OrganizationUpdateRequest(
                name = '0'
            )
        else:
            return OrganizationUpdateRequest(
        )
        """

    def testOrganizationUpdateRequest(self):
        """Test OrganizationUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
