"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.translated_labels import TranslatedLabels
globals()['TranslatedLabels'] = TranslatedLabels
from cosmotech_api.model.analysis_parameter import AnalysisParameter


class TestAnalysisParameter(unittest.TestCase):
    """AnalysisParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalysisParameter(self):
        """Test AnalysisParameter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnalysisParameter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
