"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.workspace_user_details_all_of import WorkspaceUserDetailsAllOf


class TestWorkspaceUserDetailsAllOf(unittest.TestCase):
    """WorkspaceUserDetailsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceUserDetailsAllOf(self):
        """Test WorkspaceUserDetailsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkspaceUserDetailsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
