"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.simulation_container_log import SimulationContainerLog
globals()['SimulationContainerLog'] = SimulationContainerLog
from cosmotech_api.model.simulation_container_logs import SimulationContainerLogs


class TestSimulationContainerLogs(unittest.TestCase):
    """SimulationContainerLogs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimulationContainerLogs(self):
        """Test SimulationContainerLogs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SimulationContainerLogs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
