"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.run_template_parameter_value import RunTemplateParameterValue
from cosmotech_api.model.scenario_run_all_of import ScenarioRunAllOf
from cosmotech_api.model.scenario_run_base import ScenarioRunBase
from cosmotech_api.model.scenario_run_containers import ScenarioRunContainers
globals()['RunTemplateParameterValue'] = RunTemplateParameterValue
globals()['ScenarioRunAllOf'] = ScenarioRunAllOf
globals()['ScenarioRunBase'] = ScenarioRunBase
globals()['ScenarioRunContainers'] = ScenarioRunContainers
from cosmotech_api.model.scenario_run import ScenarioRun


class TestScenarioRun(unittest.TestCase):
    """ScenarioRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScenarioRun(self):
        """Test ScenarioRun"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScenarioRun()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
