"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.8-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.scenario_run_template_parameter_value import ScenarioRunTemplateParameterValue
from cosmotech_api.model.scenario_user import ScenarioUser
globals()['ScenarioRunTemplateParameterValue'] = ScenarioRunTemplateParameterValue
globals()['ScenarioUser'] = ScenarioUser
from cosmotech_api.model.scenario import Scenario


class TestScenario(unittest.TestCase):
    """Scenario unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScenario(self):
        """Test Scenario"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Scenario()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
