# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 4.1.3-onprem
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.run_logs import RunLogs

class TestRunLogs(unittest.TestCase):
    """RunLogs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunLogs:
        """Test RunLogs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunLogs`
        """
        model = RunLogs()
        if include_optional:
            return RunLogs(
                run_id = '',
                logs = [
                    cosmotech_api.models.run_logs_entry.RunLogsEntry(
                        line = '', )
                    ]
            )
        else:
            return RunLogs(
                run_id = '',
                logs = [
                    cosmotech_api.models.run_logs_entry.RunLogsEntry(
                        line = '', )
                    ],
        )
        """

    def testRunLogs(self):
        """Test RunLogs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
