"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 2.2.0
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.twin_graph_import_info import TwinGraphImportInfo


class TestTwinGraphImportInfo(unittest.TestCase):
    """TwinGraphImportInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTwinGraphImportInfo(self):
        """Test TwinGraphImportInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TwinGraphImportInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
