"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 3.1.13
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.resource_size_info import ResourceSizeInfo
globals()['ResourceSizeInfo'] = ResourceSizeInfo
from cosmotech_api.model.runner_resource_sizing import RunnerResourceSizing


class TestRunnerResourceSizing(unittest.TestCase):
    """RunnerResourceSizing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunnerResourceSizing(self):
        """Test RunnerResourceSizing"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RunnerResourceSizing()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
