"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.scenario_analysis import ScenarioAnalysis
from cosmotech_api.model.scenario_analysis_parameter_value import ScenarioAnalysisParameterValue
from cosmotech_api.model.scenario_successful_analysis_all_of import ScenarioSuccessfulAnalysisAllOf
globals()['ScenarioAnalysis'] = ScenarioAnalysis
globals()['ScenarioAnalysisParameterValue'] = ScenarioAnalysisParameterValue
globals()['ScenarioSuccessfulAnalysisAllOf'] = ScenarioSuccessfulAnalysisAllOf
from cosmotech_api.model.scenario_successful_analysis import ScenarioSuccessfulAnalysis


class TestScenarioSuccessfulAnalysis(unittest.TestCase):
    """ScenarioSuccessfulAnalysis unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScenarioSuccessfulAnalysis(self):
        """Test ScenarioSuccessfulAnalysis"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScenarioSuccessfulAnalysis()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
