"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.run_template_parameter_value import RunTemplateParameterValue
globals()['RunTemplateParameterValue'] = RunTemplateParameterValue
from cosmotech_api.model.simulation_start_solution import SimulationStartSolution


class TestSimulationStartSolution(unittest.TestCase):
    """SimulationStartSolution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimulationStartSolution(self):
        """Test SimulationStartSolution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SimulationStartSolution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
