"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.workspace_simulator import WorkspaceSimulator
from cosmotech_api.model.workspace_user import WorkspaceUser
from cosmotech_api.model.workspace_web_app import WorkspaceWebApp
globals()['WorkspaceSimulator'] = WorkspaceSimulator
globals()['WorkspaceUser'] = WorkspaceUser
globals()['WorkspaceWebApp'] = WorkspaceWebApp
from cosmotech_api.model.workspace import Workspace


class TestWorkspace(unittest.TestCase):
    """Workspace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspace(self):
        """Test Workspace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Workspace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
