# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 5.0.0-beta3
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.workspace import Workspace

class TestWorkspace(unittest.TestCase):
    """Workspace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Workspace:
        """Test Workspace
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Workspace`
        """
        model = Workspace()
        if include_optional:
            return Workspace(
                id = 'w-0123456789ab',
                organization_id = 'o-0123456789ab',
                key = 'MyKey',
                name = 'FranceOffice',
                description = '',
                version = '1.0.0',
                tags = [
                    ''
                    ],
                create_info = cosmotech_api.models.workspace_edit_info.WorkspaceEditInfo(
                    timestamp = 56, 
                    user_id = '', ),
                update_info = cosmotech_api.models.workspace_edit_info.WorkspaceEditInfo(
                    timestamp = 56, 
                    user_id = '', ),
                solution = cosmotech_api.models.workspace_solution.WorkspaceSolution(
                    solution_id = 'sol-HqXzyCBw3_uufVPI', 
                    run_template_filter = [
                        ''
                        ], 
                    default_run_template_dataset = { }, ),
                web_app = cosmotech_api.models.workspace_web_app.WorkspaceWebApp(
                    url = '', 
                    iframes = { }, 
                    options = { }, ),
                dataset_copy = True,
                security = cosmotech_api.models.workspace_security.WorkspaceSecurity(
                    default = '', 
                    access_control_list = [
                        cosmotech_api.models.workspace_access_control.WorkspaceAccessControl(
                            id = '', 
                            role = '', )
                        ], )
            )
        else:
            return Workspace(
                id = 'w-0123456789ab',
                organization_id = 'o-0123456789ab',
                key = 'MyKey',
                name = 'FranceOffice',
                create_info = cosmotech_api.models.workspace_edit_info.WorkspaceEditInfo(
                    timestamp = 56, 
                    user_id = '', ),
                update_info = cosmotech_api.models.workspace_edit_info.WorkspaceEditInfo(
                    timestamp = 56, 
                    user_id = '', ),
                solution = cosmotech_api.models.workspace_solution.WorkspaceSolution(
                    solution_id = 'sol-HqXzyCBw3_uufVPI', 
                    run_template_filter = [
                        ''
                        ], 
                    default_run_template_dataset = { }, ),
                security = cosmotech_api.models.workspace_security.WorkspaceSecurity(
                    default = '', 
                    access_control_list = [
                        cosmotech_api.models.workspace_access_control.WorkspaceAccessControl(
                            id = '', 
                            role = '', )
                        ], ),
        )
        """

    def testWorkspace(self):
        """Test Workspace"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
