# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 5.0.0-beta3
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.run_template_parameter_group_update_request import RunTemplateParameterGroupUpdateRequest

class TestRunTemplateParameterGroupUpdateRequest(unittest.TestCase):
    """RunTemplateParameterGroupUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunTemplateParameterGroupUpdateRequest:
        """Test RunTemplateParameterGroupUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunTemplateParameterGroupUpdateRequest`
        """
        model = RunTemplateParameterGroupUpdateRequest()
        if include_optional:
            return RunTemplateParameterGroupUpdateRequest(
                description = '',
                labels = {
                    'key' : ''
                    },
                is_table = True,
                options = { },
                parent_id = '',
                parameters = [
                    ''
                    ]
            )
        else:
            return RunTemplateParameterGroupUpdateRequest(
        )
        """

    def testRunTemplateParameterGroupUpdateRequest(self):
        """Test RunTemplateParameterGroupUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
