"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.simulation_logs_options import SimulationLogsOptions


class TestSimulationLogsOptions(unittest.TestCase):
    """SimulationLogsOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimulationLogsOptions(self):
        """Test SimulationLogsOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SimulationLogsOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
