"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.13-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.workspace_user import WorkspaceUser


class TestWorkspaceUser(unittest.TestCase):
    """WorkspaceUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceUser(self):
        """Test WorkspaceUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkspaceUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
