"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.13-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.connector_parameter_group import ConnectorParameterGroup
globals()['ConnectorParameterGroup'] = ConnectorParameterGroup
from cosmotech_api.model.connector import Connector


class TestConnector(unittest.TestCase):
    """Connector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnector(self):
        """Test Connector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Connector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
