"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 1.1.3-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.workspace_file import WorkspaceFile


class TestWorkspaceFile(unittest.TestCase):
    """WorkspaceFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceFile(self):
        """Test WorkspaceFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkspaceFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
