"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 3.1.13
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.runner_job_state import RunnerJobState
from cosmotech_api.model.runner_last_run import RunnerLastRun
from cosmotech_api.model.runner_resource_sizing import RunnerResourceSizing
from cosmotech_api.model.runner_run_template_parameter_value import RunnerRunTemplateParameterValue
from cosmotech_api.model.runner_security import RunnerSecurity
from cosmotech_api.model.runner_validation_status import RunnerValidationStatus
globals()['RunnerJobState'] = RunnerJobState
globals()['RunnerLastRun'] = RunnerLastRun
globals()['RunnerResourceSizing'] = RunnerResourceSizing
globals()['RunnerRunTemplateParameterValue'] = RunnerRunTemplateParameterValue
globals()['RunnerSecurity'] = RunnerSecurity
globals()['RunnerValidationStatus'] = RunnerValidationStatus
from cosmotech_api.model.runner import Runner


class TestRunner(unittest.TestCase):
    """Runner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunner(self):
        """Test Runner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Runner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
