"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 2.2.0
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.organization_access_control import OrganizationAccessControl
globals()['OrganizationAccessControl'] = OrganizationAccessControl
from cosmotech_api.model.organization_security import OrganizationSecurity


class TestOrganizationSecurity(unittest.TestCase):
    """OrganizationSecurity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizationSecurity(self):
        """Test OrganizationSecurity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrganizationSecurity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
