# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 4.1.3-onprem
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.delete_historical_data import DeleteHistoricalData

class TestDeleteHistoricalData(unittest.TestCase):
    """DeleteHistoricalData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteHistoricalData:
        """Test DeleteHistoricalData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteHistoricalData`
        """
        model = DeleteHistoricalData()
        if include_optional:
            return DeleteHistoricalData(
                enable = True,
                poll_frequency = 56,
                time_out = 56
            )
        else:
            return DeleteHistoricalData(
                enable = True,
        )
        """

    def testDeleteHistoricalData(self):
        """Test DeleteHistoricalData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
