# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 5.0.1-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.graph_properties import GraphProperties

class TestGraphProperties(unittest.TestCase):
    """GraphProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GraphProperties:
        """Test GraphProperties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GraphProperties`
        """
        model = GraphProperties()
        if include_optional:
            return GraphProperties(
                type = '',
                source = '',
                target = '',
                name = '',
                params = ''
            )
        else:
            return GraphProperties(
        )
        """

    def testGraphProperties(self):
        """Test GraphProperties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
