"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 3.1.13
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.container_resource_sizing import ContainerResourceSizing
from cosmotech_api.model.run_container_artifact import RunContainerArtifact
globals()['ContainerResourceSizing'] = ContainerResourceSizing
globals()['RunContainerArtifact'] = RunContainerArtifact
from cosmotech_api.model.run_container import RunContainer


class TestRunContainer(unittest.TestCase):
    """RunContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunContainer(self):
        """Test RunContainer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RunContainer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
