"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import unittest

import cosmotech_api
from cosmotech_api.api.solution_api import SolutionApi  # noqa: E501


class TestSolutionApi(unittest.TestCase):
    """SolutionApi unit test stubs"""

    def setUp(self):
        self.api = SolutionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_solution(self):
        """Test case for create_solution

        Register a new solution  # noqa: E501
        """
        pass

    def test_delete_solution(self):
        """Test case for delete_solution

        Delete a solution  # noqa: E501
        """
        pass

    def test_find_all_solutions(self):
        """Test case for find_all_solutions

        List all Solutions  # noqa: E501
        """
        pass

    def test_find_solution_by_id(self):
        """Test case for find_solution_by_id

        Get the details of a solution  # noqa: E501
        """
        pass

    def test_update_solution(self):
        """Test case for update_solution

        Update a solution  # noqa: E501
        """
        pass

    def test_upload(self):
        """Test case for upload

        Upload and register a new solution  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
