# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 5.0.0-beta3
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.organization import Organization

class TestOrganization(unittest.TestCase):
    """Organization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Organization:
        """Test Organization
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Organization`
        """
        model = Organization()
        if include_optional:
            return Organization(
                id = '',
                name = '',
                create_info = cosmotech_api.models.organization_edit_info.OrganizationEditInfo(
                    timestamp = 56, 
                    user_id = '', ),
                update_info = cosmotech_api.models.organization_edit_info.OrganizationEditInfo(
                    timestamp = 56, 
                    user_id = '', ),
                security = cosmotech_api.models.organization_security.OrganizationSecurity(
                    default = '', 
                    access_control_list = [
                        cosmotech_api.models.organization_access_control.OrganizationAccessControl(
                            id = '', 
                            role = '', )
                        ], )
            )
        else:
            return Organization(
                id = '',
                name = '',
                create_info = cosmotech_api.models.organization_edit_info.OrganizationEditInfo(
                    timestamp = 56, 
                    user_id = '', ),
                update_info = cosmotech_api.models.organization_edit_info.OrganizationEditInfo(
                    timestamp = 56, 
                    user_id = '', ),
                security = cosmotech_api.models.organization_security.OrganizationSecurity(
                    default = '', 
                    access_control_list = [
                        cosmotech_api.models.organization_access_control.OrganizationAccessControl(
                            id = '', 
                            role = '', )
                        ], ),
        )
        """

    def testOrganization(self):
        """Test Organization"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
