# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 5.2.1-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.organization_member_user import OrganizationMemberUser

class TestOrganizationMemberUser(unittest.TestCase):
    """OrganizationMemberUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationMemberUser:
        """Test OrganizationMemberUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationMemberUser`
        """
        model = OrganizationMemberUser()
        if include_optional:
            return OrganizationMemberUser(
                id = '',
                role = ''
            )
        else:
            return OrganizationMemberUser(
                id = '',
                role = '',
        )
        """

    def testOrganizationMemberUser(self):
        """Test OrganizationMemberUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
