# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 3.3.1
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.run_search_state import RunSearchState

class TestRunSearchState(unittest.TestCase):
    """RunSearchState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunSearchState(self):
        """Test RunSearchState"""
        # inst = RunSearchState()

if __name__ == '__main__':
    unittest.main()
