"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.13-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.scenario_changed_parameter_value import ScenarioChangedParameterValue


class TestScenarioChangedParameterValue(unittest.TestCase):
    """ScenarioChangedParameterValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScenarioChangedParameterValue(self):
        """Test ScenarioChangedParameterValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScenarioChangedParameterValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
