"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 3.1.13
    Contact: platform@cosmotech.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.runner_last_run import RunnerLastRun


class TestRunnerLastRun(unittest.TestCase):
    """RunnerLastRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunnerLastRun(self):
        """Test RunnerLastRun"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RunnerLastRun()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
