# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 4.0.0-onprem.7
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.api.solution_api import SolutionApi


class TestSolutionApi(unittest.TestCase):
    """SolutionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SolutionApi()

    def tearDown(self) -> None:
        pass

    def test_add_or_replace_parameter_groups(self) -> None:
        """Test case for add_or_replace_parameter_groups

        Add Parameter Groups. Any item with the same ID will be overwritten
        """
        pass

    def test_add_or_replace_parameters(self) -> None:
        """Test case for add_or_replace_parameters

        Add Parameters. Any item with the same ID will be overwritten
        """
        pass

    def test_add_or_replace_run_templates(self) -> None:
        """Test case for add_or_replace_run_templates

        Add Run Templates. Any item with the same ID will be overwritten
        """
        pass

    def test_add_solution_access_control(self) -> None:
        """Test case for add_solution_access_control

        Add a control access to the Solution
        """
        pass

    def test_create_solution(self) -> None:
        """Test case for create_solution

        Register a new solution
        """
        pass

    def test_delete_solution(self) -> None:
        """Test case for delete_solution

        Delete a solution
        """
        pass

    def test_delete_solution_run_template(self) -> None:
        """Test case for delete_solution_run_template

        Remove the specified Solution Run Template
        """
        pass

    def test_find_all_solutions(self) -> None:
        """Test case for find_all_solutions

        List all Solutions
        """
        pass

    def test_find_solution_by_id(self) -> None:
        """Test case for find_solution_by_id

        Get the details of a solution
        """
        pass

    def test_get_solution_access_control(self) -> None:
        """Test case for get_solution_access_control

        Get a control access for the Solution
        """
        pass

    def test_get_solution_security(self) -> None:
        """Test case for get_solution_security

        Get the Solution security information
        """
        pass

    def test_get_solution_security_users(self) -> None:
        """Test case for get_solution_security_users

        Get the Solution security users list
        """
        pass

    def test_remove_all_run_templates(self) -> None:
        """Test case for remove_all_run_templates

        Remove all Run Templates from the Solution specified
        """
        pass

    def test_remove_all_solution_parameter_groups(self) -> None:
        """Test case for remove_all_solution_parameter_groups

        Remove all Parameter Groups from the Solution specified
        """
        pass

    def test_remove_all_solution_parameters(self) -> None:
        """Test case for remove_all_solution_parameters

        Remove all Parameters from the Solution specified
        """
        pass

    def test_remove_solution_access_control(self) -> None:
        """Test case for remove_solution_access_control

        Remove the specified access from the given Organization Solution
        """
        pass

    def test_set_solution_default_security(self) -> None:
        """Test case for set_solution_default_security

        Set the Solution default security
        """
        pass

    def test_update_solution(self) -> None:
        """Test case for update_solution

        Update a solution
        """
        pass

    def test_update_solution_access_control(self) -> None:
        """Test case for update_solution_access_control

        Update the specified access to User for a Solution
        """
        pass

    def test_update_solution_run_template(self) -> None:
        """Test case for update_solution_run_template

        Update the specified Solution Run Template
        """
        pass


if __name__ == '__main__':
    unittest.main()
