# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 5.1.1-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.workspace_members import WorkspaceMembers

class TestWorkspaceMembers(unittest.TestCase):
    """WorkspaceMembers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceMembers:
        """Test WorkspaceMembers
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceMembers`
        """
        model = WorkspaceMembers()
        if include_optional:
            return WorkspaceMembers(
                users = [
                    cosmotech_api.models.workspace_member_user.WorkspaceMemberUser(
                        id = '', 
                        role = '', )
                    ],
                groups = [
                    cosmotech_api.models.workspace_member_group.WorkspaceMemberGroup(
                        id = '', 
                        role = '', 
                        users = [
                            ''
                            ], )
                    ]
            )
        else:
            return WorkspaceMembers(
                users = [
                    cosmotech_api.models.workspace_member_user.WorkspaceMemberUser(
                        id = '', 
                        role = '', )
                    ],
                groups = [
                    cosmotech_api.models.workspace_member_group.WorkspaceMemberGroup(
                        id = '', 
                        role = '', 
                        users = [
                            ''
                            ], )
                    ],
        )
        """

    def testWorkspaceMembers(self):
        """Test WorkspaceMembers"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
