"""
    Cosmo Tech Plaform API

    Cosmo Tech Platform API  # noqa: E501

    The version of the OpenAPI document: 0.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cosmotech_api
from cosmotech_api.model.workspace_user import WorkspaceUser
from cosmotech_api.model.workspace_user_details_all_of import WorkspaceUserDetailsAllOf
globals()['WorkspaceUser'] = WorkspaceUser
globals()['WorkspaceUserDetailsAllOf'] = WorkspaceUserDetailsAllOf
from cosmotech_api.model.workspace_user_details import WorkspaceUserDetails


class TestWorkspaceUserDetails(unittest.TestCase):
    """WorkspaceUserDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceUserDetails(self):
        """Test WorkspaceUserDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkspaceUserDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
