# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 3.3.4
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cosmotech_api.models.organization_service import OrganizationService

class TestOrganizationService(unittest.TestCase):
    """OrganizationService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationService:
        """Test OrganizationService
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationService`
        """
        model = OrganizationService()
        if include_optional:
            return OrganizationService(
                cloud_service = '',
                base_uri = '',
                platform_service = '',
                resource_uri = '',
                credentials = { }
            )
        else:
            return OrganizationService(
        )
        """

    def testOrganizationService(self):
        """Test OrganizationService"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
