# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 4.0.1-SNAPSHOT
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class IoTypesEnum(str, Enum):
    """
    The read and write capabilities of connector
    """

    """
    allowed enum values
    """
    READ = 'read'
    WRITE = 'write'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IoTypesEnum from a JSON string"""
        return cls(json.loads(json_str))


