# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 5.1.0-rc2
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RunnerStatus(str, Enum):
    """
    the status of the runner
    """

    """
    allowed enum values
    """
    OK = 'Ok'
    ARCHIVED = 'Archived'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RunnerStatus from a JSON string"""
        return cls(json.loads(json_str))


