# coding: utf-8

"""
    Cosmo Tech Platform API

    Cosmo Tech Platform API

    The version of the OpenAPI document: 3.3.1
    Contact: platform@cosmotech.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Validator(BaseModel):
    """
    a Validator to validate a Dataset
    """ # noqa: E501
    id: StrictStr = Field(description="the Validator id")
    name: StrictStr = Field(description="the Validator name")
    description: Optional[StrictStr] = Field(default=None, description="the Validator description")
    repository: StrictStr = Field(description="the registry repository containing the Validator image")
    version: StrictStr = Field(description="the Validator version MAJOR.MINOR.PATCH. Must be aligned with an existing repository tag")
    owner_id: Optional[StrictStr] = Field(default=None, description="the User id which own this Validator", alias="ownerId")
    url: Optional[StrictStr] = Field(default=None, description="an optional URL link to Validator page")
    tags: Optional[List[StrictStr]] = Field(default=None, description="the list of tags")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "repository", "version", "ownerId", "url", "tags"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Validator from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "owner_id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Validator from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "repository": obj.get("repository"),
            "version": obj.get("version"),
            "ownerId": obj.get("ownerId"),
            "url": obj.get("url"),
            "tags": obj.get("tags")
        })
        return _obj


